name: Build and Publish Docker Image

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.20.4
        cache: 'npm'

    # Step 3: Install dependencies
    - name: npm install, build, and test
      run: |
        npm install

    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Build and tag the Docker image
    - name: Build and tag Docker image
      run: |
        docker build -t my-express-app:latest .
        docker tag my-express-app:latest ${{ secrets.DOCKER_USERNAME }}/my-express-app:latest

    # Step 6: Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-express-app:latest
